version: '2'
services:
    web:
        image: eboraas/apache-php
        build: .
        ports:
            - "8111:80"
            - "4431:443"
        volumes:
            - ./code/:/var/www/html/
